####################------type-Load-balancer-----------########################
apiVersion: v1
kind: Service
metadata:
  name: example-service
# To set the load balancer as a internal load balancer 
# annotations: 
#   service.beta.kubernetes.io/aws-load-balancer-internal: "true"
# for internet facing 
#   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: example
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer
 
 
 
########################------------command to create type load balancer service---------------#################################
  kubectl expose deployment <deployment-name> --port=8765 --target-port=9376 \
        --name=<service-name> --type=LoadBalancer
###################-----NodePort-----#######################
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
  
