#####CREATING PRIORITYCLASS
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: prod-pc
# priority can be defained from -1000000000-1000000000
value: 4000000 
globalDefault: false
description: >-
    (Optional) This priority class should only be used for all prod pods.
# command:- kubectl get pc 
    
---
######DEPLOYMENT 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image
# here we will refer priorityclass name
      priorityClassName: prod-pc
