apiVersion: v1
kind: Secret
metadata:
  name: <secretName>
type: Opaque
stringData:
  myPassword: <yourpassword>
  
......
- name: MONGO_INITDB_ROOT_PASSWORD
  valueForm:
    secretKeyRef:
      name: <secretName>
      key: <myPassword>---give that name
